Feature/filter rooms
lauraguerra1/overlook pull request #6
Opened 2023-06-10 01:33 UTC by lauraguerra1

This PR will 
- Add a modal to view room booking details 
- GET bookings and rooms upon searching for rooms
- Filter retrieved rooms by searched date, customer budget, and room type 

Additional Notes 
- Room modal does not yet reflect accurate room information and currently reflects mock data
- Reserve now button is not yet functional

Testing Notes 
- Attempt to search for a room with different filters
- Type in a date that has passed to check for error handling 
- run `npm test` to check all tests are passing

2023-06-10 23:17 UTC, rachelsoae requested changes
Just a few small suggestions. As usual, your code is gorgeous and I have learned a lot from what you're doing :) Fantastic work.

2023-06-10 23:17 UTC, rachelsoae commented on test/date-test.js
6 of 17 date tests are currently failing; a few are returning the incorrect month, and a few are returning the incorrect day.

2023-06-10 23:17 UTC, rachelsoae commented on src/apicalls.js
⭐️⭐️⭐️⭐️⭐️
I love this clever use of interpolation to make your GET function super dynamic. Gorgeous.

2023-06-10 23:17 UTC, rachelsoae commented on src/domUpdates.js
> -  filterBtn.classList.add('hidden');
Consider adding helper functions to show/hide.
This will help DRY up showDash and switchToHome.
It's not going to shorten your code line for line, but it will avoid some of this repetition and may be more readable.

2023-06-10 23:17 UTC, rachelsoae commented on src/domUpdates.js
> -    residentialsuite:
👏👏👏 beautiful method of adding dynamic altText.

2023-06-10 23:17 UTC, rachelsoae commented on src/css/styles.css
>    font-family: 'Maven Pro', sans-serif;
lines 56-58; Consider utilizing shorthand for your margin size. 
margin: [top, right, bottom, left]
if you want the top and sides to be the same, margin: [top, sides]
then, if you want the left margin to be overwritten in some way, you can do a margin-left as a separate property.
Let me know if the way I've explained this is confusing.

2023-06-11 14:27 UTC, lauraguerra1 commented on test/date-test.js
I had a calendar bug that I caught and pushed the fix after I originally put up this PR. The tests are passing on my end, would you mind pulling down the most recent version of this branch again and running the tests on your end? I want to double-check that it is just the branch's old version, not an environmental issue.

2023-06-11 14:39 UTC, lauraguerra1 commented on src/css/styles.css
>    font-family: 'Maven Pro', sans-serif;
This is super helpful! Thank you! 

Lines 56-58 are replaced with line 56: 
```
  margin: 1% 2% 1% 0;
```

2023-06-11 16:21 UTC, rachelsoae commented on test/date-test.js
Pulled down again and still failing 6, though I do see I was working on main yesterday and that's why I only had 17 tests (now I see 31).

2023-06-11 18:36 UTC, taranveersingh93 approved these changes
All tests passing and solid functionality

2023-06-11 20:27 UTC, rachelsoae commented on test/date-test.js
Glad to hear that everything is passing. Ok to merge.

2023-06-11 20:27 UTC, rachelsoae approved these changes

2023-06-11 20:27 UTC, merged